# Generated by Django 3.2.9 on 2021-11-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Не более 20 символов', max_length=20, unique=True, verbose_name='Кличка')),
                ('age', models.CharField(blank=True, help_text='не более 30 симоволов', max_length=30, verbose_name='возраст')),
                ('description', models.TextField(help_text='не более 200 символов', max_length=200, verbose_name='Описание')),
                ('date', models.DateField(blank=True, help_text='Дата появления в приюте', verbose_name='Дата появления в приюте')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='электронная почта для связи')),
                ('comment', models.TextField(max_length=200, verbose_name='контактная информация')),
                ('status', models.BooleanField(default=True, help_text='Ищет ли дом сейчас', null=True, verbose_name='Ищет дом')),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Не более 20 символов', max_length=20, unique=True, verbose_name='Название приюта')),
                ('description', models.TextField(help_text='не более 200 символов', max_length=200, verbose_name='Описание и контакты')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='электронная почта для связи')),
                ('link', models.URLField(blank='True', verbose_name='Ссылка')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
