# Generated by Django 3.2.9 on 2021-12-01 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalone',
            options={'ordering': ['nickname'], 'verbose_name': 'Животное', 'verbose_name_plural': 'Животные'},
        ),
        migrations.AlterModelOptions(
            name='shelter',
            options={'ordering': ['name'], 'verbose_name': 'Приют', 'verbose_name_plural': 'Приюты'},
        ),
        migrations.AddField(
            model_name='animalone',
            name='shelter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='animals.shelter', verbose_name='Приют'),
        ),
    ]
