# Generated by Django 3.2.9 on 2021-12-02 13:41

import animals.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animals', '0002_auto_20211201_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalone',
            name='cover',
            field=models.ImageField(null=True, upload_to='media/images/', verbose_name='Основное изображение'),
        ),
        migrations.AddField(
            model_name='animalone',
            name='photos',
            field=models.ImageField(null=True, upload_to=animals.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='animalone',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
